name: Called Secrets Workflow
on:
  workflow_call:
    inputs:
      environment:
        description: 'the environment to deploy to'
        required: true
        type: string
      secret_prefix:
        required: true
        type: string

jobs:
  environment-test:
    runs-on: ubuntu-latest
    steps:
      - name: Secret Prefix Test
        run: |
            if [[ ${{ inputs.secret_prefix }} == 'EDCAR' ]]
            then
              echo "EDCAR is secret prefix"
              #echo "Edcar Region set by way of env file!"
              #echo "Role: ${{env.role_name}}"
            fi
      - name: Echo Inherited Secrets
        id: echo-inherited-secrets
        run: |
          echo $EDCAR_ROLE
        env:
          EDCAR_ROLE: ${{ secrets.EDCAR_ROLE_NAME }}
