name: Called Workflow
on:
  workflow_call:
    inputs:
      environment:
        description: 'the environment to deploy to'
        required: true
        type: string

jobs:
  prepare-environment:
    runs-on: ubuntu-latest
    steps:
    - name: Map option to environment
      run: |
        if [[ '${{inputs.environment}}' == 'DEV' ]]
        then
          echo "DEV to EDCAR"
          echo "SECRET_PREFIX=EDCAR" >> $GITHUB_ENV
        elif [[ '${{inputs.environment}}' == 'STAGING' ]] 
        then
          echo "STAGING to PREPROD"
          echo "SECRET_PREFIX=PREPROD" >> $GITHUB_ENV
        fi
    - name: Set secret names as env vars
      run: |
        echo "REGION_NAME=${{env.SECRET_PREFIX}}_REGION" >> $GITHUB_ENV

  environment-test:
    needs: prepare-environment
    runs-on: ubuntu-latest
    steps:
      - name: Secret Test 3
        run: |
            if [[ '$REGION_NAME' == 'edcar_region' ]]
            then
              echo "Edcar Region!"
            elif [[ '$REGION_NAME' == 'preprod_region' ]]
            then
              echo "Preprod Region!"
            fi
        env:
          REGION_NAME: ${{env.REGION_NAME}}
