name: Download Artifact
on:
  workflow_call:

jobs:
  deb-download:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: date.out
          path: ./

      - name: cat artifact file
        run: |
          cat ./date.out

