name: _notify
on:
  workflow_call:
    inputs:
      environment:
        description: 'the environment to deploy to'
        required: true
        type: string
      simulate_deployment_result:
        type: string
        required: true

jobs:
  notify_whomever:
    runs-on: ubuntu-latest
    steps:
    - name: Notify
      id: notify
      run: |
        echo "##########"
        echo "Outcome of simulate_deployment: ${{inputs.simulate_deployment_result}}"
        echo "##########"
