name: _notify_slack
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      git_sha:
        type: string
        default: "012356789ABCDEF"
        required: true
      latest_tag:
        required: true
        default: "EVS"
        type: string
      deploy-status:
        required: true
        default: "true"
        type: string

jobs:
  artifact-notify_slack:
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest
    steps:
      - name: Check tag input
        run: |
          if [ -z ${{inputs.latest_tag}} ]
          then
            echo "inputs.latest_tag is empty; using github.ref_name"
            echo "checked_tag=${{github.ref_name}}" >> $GITHUB_ENV
          else
            echo "inputs.latest_tag is not empty"
            echo "checked_tag=${{inputs.latest_tag}}" >> $GITHUB_ENV
          fi
      - name: Post a success message to Slack channel
        if: ${{inputs.deploy-status == 'true'}}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{secrets.SLACK_BOT_TOKEN}}
          payload: |
            errors: true
            channel: ${{secrets.SLACK_CHANNEL_ID}}
            emoji: 
            blocks:
              - type: "section"
                text: 
                  type: "mrkdwn"
                  text: "Successfully deployed `dotorg-next` to `${{inputs.environment}}` :rocket:\n
                        Hash: `${{ inputs.git_sha }}`\nTag: `${{env.checked_tag }}`\n
                        <https://www.pbs.org|www.pbs.org>"
