name: Caller Secrets Workflow
on:
  workflow_dispatch:
    inputs:
      aws_profile:
        type: choice
        options:
          - DEV
          - STAGING
          - PROD
permissions: read-all

jobs:
  prepare-environment:
    runs-on: ubuntu-latest
    outputs:
      secret_prefix: ${{ steps.map-input-to-env.outputs.SECRET_PREFIX }}
    steps:
      - name: Map option to environment
        id: map-input-to-env
        run: |
          if [[ '${{inputs.aws_profile}}' == 'DEV' ]]
          then
            echo "DEV to EDCAR"
            echo "SECRET_PREFIX=EDCAR" >> $GITHUB_OUTPUT
          fi

  foo:
    runs-on: ubuntu-latest
    needs: prepare-environment
    steps:
      - name: Check output var
        id: output-var-check
        run: |
          echo "Prefix: $SECRET_PREFIX"
        env:
          SECRET_PREFIX: ${{ needs.prepare-environment.outputs.secret_prefix }}"

  call_called_secrets:
    needs: prepare-environment
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/_called_secrets.yml
    with:
      environment: ${{inputs.aws_profile}}
      secret_prefix: ${{ needs.prepare-environment.outputs.secret_prefix }}
    secrets: inherit
