name: Caller Secrets Workflow
on:
  workflow_dispatch:
    inputs:
      aws_profile:
        type: choice
        options:
          - DEV
          - STAGING
          - PROD
permissions: read-all

jobs:
  prepare-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Map option to environment
        id: map-input-to-env
        run: |
          if [[ '${{inputs.environment}}' == 'DEV' ]]
          then
            echo "DEV to EDCAR"
            echo "SECRET_PREFIX=EDCAR" >> $GITHUB_ENV
          elif [[ '${{inputs.environment}}' == 'STAGING' ]] 
          then
            echo "STAGING to PREPROD"
            echo "SECRET_PREFIX=PREPROD" >> $GITHUB_ENV
          fi
      - name: Set secret names as env vars in env file
        id: set-env-file-values
        run: |
          echo "region_name=${{env.SECRET_PREFIX}}_REGION" >> "$GITHUB_ENV"
          echo "role_name=${{env.SECRET_PREFIX}}_ROLE" >> "$GITHUB_ENV" 

  call_called_secrets:
    if: github.ref == 'refs/heads/main'
    uses: socketbox/actions_tests/.github/workflows/_called_secrets.yml@main
    with:
      environment: ${{inputs.aws_profile}}
      secret_prefix: ${{env.SECRET_PREFIX}}
    secrets: inherit
