name: Caller Workflow
on:
  workflow_dispatch:
    inputs:
      aws_profile:
        type: choice
        options:
          - DEV
          - STAGING
          - PROD
permissions: read-all

jobs:
  call_called:
    if: github.ref == 'refs/heads/main'
    uses: socketbox/actions_tests/.github/workflows/_called.yml@main
    with:
      environment: ${{inputs.aws_profile}}
