name: Invalidate Edge Cache
on:
  workflow_dispatch:
    inputs:
      paths:
        description: 'Space-delimited paths to invalidate'
        type: string
        default: |
          /explore*
          /livestream*
          /show*
          /my-station*
          /_next*
          /video*
          /search*
          /api*
          /
      production:
        description: 'Invalidate production dist.'
        default: false
        type: boolean
      staging:
        description: 'Invalidate staging dist.'
        type: boolean
        default: true
      confirmation:
        description: "Confirm production invalidation"
        required: false
        type: boolean
        default: false

  workflow_call:
    inputs:
      paths:
        description: 'Space-delimited paths to invalidate'
        type: string
        default: |
          /explore* 
          /livestream* 
          /show* 
          /my-station* 
          /_next* 
          /video* 
          /search* 
          /api* 
          /
      production:
        description: 'Invalidate production dist.'
        default: false
        type: boolean
      staging:
        description: 'Invalidate staging dist.'
        type: boolean
        default: true
      confirmation:
        description: "Confirm production invalidation"
        required: false
        type: boolean
        default: false

permissions:
  #actions: read
  id-token: write
  #contents: write
  #packages: write

jobs:
  # because of limitations in jobs.<job>.if
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      #https://github.com/actions/github-script?tab=readme-ov-file#reading-step-results
      edges: ${{steps.build-matrix.outputs.result}}
    steps:
      - name: Build matrix
        id: build-matrix
        shell: python
        run: |
          import json
          import os
            
          # GitHub Actions inputs are available as environment variables
          production = os.environ.get('INPUT_PRODUCTION', '').lower()
          confirmation = os.environ.get('INPUT_CONFIRMATION', '').lower()
          staging = os.environ.get('INPUT_STAGING', '').lower()

          print(f"production: {production}")
          print(f"confirmation: {confirmation}")
          print(f"staging: {staging}")

          edges = []
          if production == 'true' and confirmation == 'true':
              edges.append('pbs-digi-prod')
          if staging == 'true':
              edges.append('pbs-digi-preprod')

          print(f"edges: {edges}")

          # Write to GITHUB_OUTPUT environment file
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
            print(f'result={json.dumps(edges)}', file=fh)

        env:
          INPUT_PRODUCTION: ${{ inputs.production }}
          INPUT_CONFIRMATION: ${{ inputs.confirmation }}
          INPUT_STAGING: ${{ inputs.staging }}