name: Main Caller Workflow
on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/invalidate_edge.yml
    with:
      paths: "/ /explore*"
      production: false
      staging: true
      confirmation: false
