name: Tag and Notify
on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: 'Git reference to deploy'
        required: true
        default: 'main'
        type: string
      confirmation:
        description: "Confirm production deployment"
        required: false
        type: boolean
        default: false

jobs:
  tag-release:
    # change me back to true after testing
    if: github.event.inputs.confirmation && needs.prod-deploy.outputs.deploy_status == 'true'
    uses: ./.github/workflows/_tag.yml
    secrets: inherit
    with:
      environment: "pbs-digi-prod"
      git_sha: "0123456789ABCDEF"
      latest_tag: "EVS"
      deploy-status: "true"
