name: Tag and Notify
on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: 'Git reference to deploy'
        required: true
        default: 'main'
        type: string
      confirmation:
        description: "Confirm production deployment"
        required: false
        type: boolean
        default: false

permissions:
  actions: read
  id-token: write
  contents: write
  packages: write

jobs:
  slack-notifications:
    uses: ./.github/workflows/_notify-slack.yml
    secrets: inherit
    with:
      environment: "pbs-digi-prod"
      git_sha: "0123456789ABCDEF"
      latest_tag: "EVS"
      deploy-status: "true"
